name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: maven-build
        uses: actions/setup-java@v4
        with:
            distribution: ${{vars.DISTRIBUTION}}
            java-version: ${{vars.VERSION}}
      - run: mvn clean package

      - name: Show Target
        run: ls -la target

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
           name: my-artifact
           path: target/*.jar
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact

      - name: verify artifact
        run: find . -name ".jar"
