name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print Files
        run: ls -la

      - name: print
        run: echo "Hello, World!"
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: print
        run: echo "testing"
