name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: ${{vars.DISTRIBUTION}}
          java-version: ${{vars.VERSION}}

      - name: Build
        run: mvn clean compile

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: ${{vars.DISTRIBUTION}}
          java-version: ${{vars.VERSION}}

      - name: Test
        run: mvn test
  package:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: ${{vars.DISTRIBUTION}}
          java-version: ${{vars.VERSION}}

      - name: Package
        run: mvn package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: target/*.jar

      - name: deploy
        run: echo "Deploying the application..."
